//
// Generated file, do not edit! Created by opp_msgtool 6.1 from CustomMessage.msg.
//

#ifndef __CUSTOMMESSAGE_M_H
#define __CUSTOMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CustomMessage;
/**
 * Class generated from <tt>CustomMessage.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CustomMessage
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int header; // the sequence number
 *     string payload; // the payload after byte stuffing
 *     string trailer; // the parity byte
 *     int type; // Data=2,ACK=1,NACK=0.
 *     int ack; // the ACK or NACK number
 * }
 * </pre>
 *
 * CustomMessage_Base is only useful if it gets subclassed, and CustomMessage is derived from it.
 * The minimum code to be written for CustomMessage is the following:
 *
 * <pre>
 * class CustomMessage : public CustomMessage_Base
 * {
 *   private:
 *     void copy(const CustomMessage& other) { ... }

 *   public:
 *     CustomMessage(const char *name=nullptr, short kind=0) : CustomMessage_Base(name,kind) {}
 *     CustomMessage(const CustomMessage& other) : CustomMessage_Base(other) {copy(other);}
 *     CustomMessage& operator=(const CustomMessage& other) {if (this==&other) return *this; CustomMessage_Base::operator=(other); copy(other); return *this;}
 *     virtual CustomMessage *dup() const override {return new CustomMessage(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from CustomMessage_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(CustomMessage)
 * </pre>
 */
class CustomMessage_Base : public ::omnetpp::cPacket
{
  protected:
    int header = 0;
    omnetpp::opp_string payload;
    omnetpp::opp_string trailer;
    int type = 0;
    int ack = 0;

  private:
    void copy(const CustomMessage_Base& other);

  protected:
    bool operator==(const CustomMessage_Base&) = delete;
    // make constructors protected to avoid instantiation
    CustomMessage_Base(const CustomMessage_Base& other);
    // make assignment operator protected to force the user override it
    CustomMessage_Base& operator=(const CustomMessage_Base& other);

  public:
    CustomMessage_Base(const char *name=nullptr, short kind=0);

    virtual ~CustomMessage_Base();

    virtual CustomMessage_Base *dup() const override {
        return new CustomMessage_Base(*this);
    }
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHeader() const;
    virtual void setHeader(int header);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual const char * getTrailer() const;
    virtual void setTrailer(const char * trailer);

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getAck() const;
    virtual void setAck(int ack);
};


namespace omnetpp {

template<> inline CustomMessage_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<CustomMessage_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMMESSAGE_M_H

