//
// Generated file, do not edit! Created by opp_msgtool 6.0 from our_message.msg.
//

#ifndef __OUR_MESSAGE_M_H
#define __OUR_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Our_message;
/**
 * Class generated from <tt>our_message.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Our_message
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int header; // the sequence number
 *     string payload; // the payload after byte stuffing
 *     string trailer; // the parity byte
 *     int type; // Data=2,ACK=1,NACK=0.
 *     int ack; // the ACK or NACK number
 * }
 * </pre>
 *
 * Our_message_Base is only useful if it gets subclassed, and Our_message is derived from it.
 * The minimum code to be written for Our_message is the following:
 *
 * <pre>
 * class Our_message : public Our_message_Base
 * {
 *   private:
 *     void copy(const Our_message& other) { ... }

 *   public:
 *     Our_message(const char *name=nullptr, short kind=0) : Our_message_Base(name,kind) {}
 *     Our_message(const Our_message& other) : Our_message_Base(other) {copy(other);}
 *     Our_message& operator=(const Our_message& other) {if (this==&other) return *this; Our_message_Base::operator=(other); copy(other); return *this;}
 *     virtual Our_message *dup() const override {return new Our_message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Our_message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Our_message)
 * </pre>
 */
class Our_message_Base : public ::omnetpp::cPacket
{
  protected:
    int header = 0;
    omnetpp::opp_string payload;
    omnetpp::opp_string trailer;
    int type = 0;
    int ack = 0;

  private:
    void copy(const Our_message_Base& other);

  protected:
    bool operator==(const Our_message_Base&) = delete;
    // make constructors protected to avoid instantiation
    Our_message_Base(const char *name=nullptr, short kind=0);
    Our_message_Base(const Our_message_Base& other);
    // make assignment operator protected to force the user override it
    Our_message_Base& operator=(const Our_message_Base& other);

  public:
    virtual ~Our_message_Base();
    virtual Our_message_Base *dup() const override {return new Our_message_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHeader() const;
    virtual void setHeader(int header);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual const char * getTrailer() const;
    virtual void setTrailer(const char * trailer);

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getAck() const;
    virtual void setAck(int ack);
};


namespace omnetpp {

template<> inline Our_message_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<Our_message_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OUR_MESSAGE_M_H

